src/applications/products/urls.py
from django.urls import path
from applications.products.views import (
    ProductListView, ProductDetailView,
    products_list_view, products_detail_view,
    ProductFeaturedDetailView, ProductFeaturedListView,
    ProductDetailSlugView,
)

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    # path('products/<int:pk>/', ProductDetailView.as_view()),
    path('<slug:slug>/', ProductDetailSlugView.as_view(), name='detail'),

    path('featured/<int:pk>/', ProductFeaturedDetailView.as_view(),),
    path('featured/', ProductFeaturedListView.as_view(),),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include, re_path
from .views import (
    home_page, about_page, contact_page,
    login_page, register_page,
)

# from products.views import (
#     ProductListView, ProductDetailView,
#     products_list_view, products_detail_view,
#     ProductFeaturedDetailView, ProductFeaturedListView,
#     ProductDetailSlugView,
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name="home"),
    path('about/', about_page, name="about"),
    path('contact/', contact_page, name="contact"),

    path('products/', include(("applications.products.urls", 'applications.products'), namespace='products')),
    # path('products-fbv/', products_list_view, name='productsfbv'),

    # path('products/<int:pk>/', ProductDetailView.as_view()),
    # path('products/<slug:slug>/', ProductDetailSlugView.as_view()),


    # path('products-fbv/<int:pk>/', products_detail_view, name='products-fbv'),

    # path('featured/<int:pk>/', ProductFeaturedDetailView.as_view(),),
    # path('featured/', ProductFeaturedListView.as_view(),),

    path('login/', login_page, name="login_page"),
    path('register/', register_page, name="register_page"),
    path('carts/', include('applications.cart.urls')),
    path('users/', include('applications.users.urls')),
    re_path(r'^about/$', about_page),
    path('orders/', include('applications.orders.urls')),
    path('api/v1/', include('applications.shop_api.urls')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/css.html
{% load static  %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/main.css' %}">

    

src/templates/base/js.html
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class='container'>
        <a class="navbar-brand" href="{{ home_url }}">
            <img src="//getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30"
                class="d-inline-block align-top" alt="">
            {% if brand_name %} {{brand_name }} {% else %} Shop Market{% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                    <a class="nav-link" href="{{ contact_url }}">Contact</a>
                </li>
                <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                    <a class="nav-link" href="{{ product_list_url }}">Products</a>
                </li>


                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item {% if request.path == account_url %}active{% endif %}"
                            href="{{ account_url }}">Home</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                    <a class="nav-link" href="{{ register_url }}">Register</a>
                </li>
                <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                    <a class="nav-link" href="{{ login_url }}">Login</a>
                </li>
                {% endif %}


                <li class="nav-item">
                    <span class='bg-danger'> In Cart - {{request.session.cart_items}} </span>
                </li>
                {% if page_products %}
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search"
                        aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>